services:
  postgres1:
    image: postgres:latest
    container_name: postgres1
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      pg_network:
        aliases:
          - postgres1
    command: postgres -c 'max_connections=200'

  postgres2:
    image: postgres:latest
    container_name: postgres2
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      pg_network:
        aliases:
          - postgres2
    command: postgres -c 'max_connections=200'

  postgres3:
    image: postgres:latest
    container_name: postgres3
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      pg_network:
        aliases:
          - postgres3
    command: postgres -c 'max_connections=200'

networks:
  pg_network:
    driver: bridge